Docker Support
buffrr/letsdane pull request #3
Opened 2021-01-16 02:50 UTC by Anunayj

Added Docker support! Also added Examples on how to run it. Might wanna run your own DockerHub repo. Current one should always be up with master with delay of about ~1hr.

2021-01-16 03:04 UTC, Anunayj commented
Docker Image is ~46 MB (Compressed) and ~108MB (Uncompressed), golang is not included in the image.

2021-01-16 07:11 UTC, Anunayj commented
Some Useful gists you may wanna add to Readme.md
https://gist.github.com/Anunayj/fa03887a368f5724f6a26ec2a8396a7f
https://gist.github.com/Anunayj/4b75d5cefac875ba51d830d57785c44c

2021-01-18 01:39 UTC, buffrr requested changes
Great work! The reademe needs a few changes but the Dockerfile looks good so far.

2021-01-18 01:39 UTC, buffrr commented on README.md
> +### Docker CLI
You can put Docker usage after Handshake section so it's easier to notice. For now you can instruct users to build their own image using `docker build -t letsdane .` and use that in the docker run example (i'm planning to maintain images with tagged versions on docker hub but not at the moment).

2021-01-18 01:39 UTC, buffrr commented on README.md
> +### Docker-compose
It's easy to figure out how to use docker-compose based on the docker run example so there is no need for this section. it's better to keep the readme short

2021-01-18 02:42 UTC, Anunayj commented
Reorganized The Readme, and made a small change with the docker run example, instead of listening on `0.0.0.0` it should listen on localhost. I felt it was safer and akin to how letsdane binary works.

2021-01-18 03:17 UTC, buffrr approved these changes
Looks good! Yeah there is no need for the proxy to listen on 0.0.0.0 by default (we should probably change that in the binary too to listen on `127.0.0.1:8080` instead of `:8080`).

2021-01-18 03:19 UTC, merged